const comidas = [
  {
    name: "Filete de Ternera",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920200/restaurantes%20y%20usuarios/hamburguer/Filete_hklnsb.jpg",
    description: "Un delicioso filete de ternera a la parrilla",
    price: 24.5,
    dietaryPreferences: "Carnívoro",
    allergen: ["Picante"],
  },
  {
    name: "Salmón a la Parrilla",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920201/restaurantes%20y%20usuarios/hamburguer/salmon_lqftgu.jpg",
    description: "Un saludable salmón a la parrilla con limón y eneldo",
    price: 22.0,
    dietaryPreferences: "Pescatarian",
    allergen: ["Pescado"],
  },
  {
    name: "Ensalada César",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920200/restaurantes%20y%20usuarios/hamburguer/cesar_zguaie.jpg",
    description: "Una fresca ensalada César con pollo a la parrilla",
    price: 15.0,
    dietaryPreferences: "Vegetariano",
    allergen: ["Gluten", "Lácteos", "Huevos", "Trigo"],
  },
  {
    name: "Pasta Alfredo",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920200/restaurantes%20y%20usuarios/hamburguer/pasta_lvunjq.jpg",
    description: "Pasta Alfredo cremosa con champiñones y parmesano",
    price: 18.5,
    dietaryPreferences: "Vegetariano",
    allergen: ["Gluten", "Lácteos", "Trigo"],
  },
  {
    name: "Pizza Margarita",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920201/restaurantes%20y%20usuarios/hamburguer/piza_fwhq44.webp",
    description: "Una clásica pizza Margarita con tomate y mozzarella",
    price: 12.0,
    dietaryPreferences: "Vegetariano",
    allergen: ["Gluten", "Lácteos", "Trigo"],
  },
  {
    name: "Enchiladas de Pollo",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920200/restaurantes%20y%20usuarios/hamburguer/enchilada_kzhg7m.jpg",
    description: "Enchiladas de pollo con salsa de tomate picante",
    price: 14.5,
    dietaryPreferences: "Carnívoro",
    allergen: ["Gluten", "Lácteos", "Trigo"],
  },
  {
    name: "Ensalada de Quinua",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920202/restaurantes%20y%20usuarios/hamburguer/quinua_ez1pwj.jpg",
    description: "Ensalada de quinua con aguacate y pimientos",
    price: 16.0,
    dietaryPreferences: "Vegano",
    allergen: [],
  },
  {
    name: "Tacos de Carne Asada",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920201/restaurantes%20y%20usuarios/hamburguer/tacos_vgpbji.jpg",
    description: "Tacos de carne asada con cebolla y cilantro",
    price: 13.5,
    dietaryPreferences: "Carnívoro",
    allergen: ["Gluten", "Trigo"],
  },
  {
    name: "Sopa de Tomate",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920201/restaurantes%20y%20usuarios/hamburguer/sopa_ezcnta.webp",
    description: "Sopa de tomate casera con crutones",
    price: 8.0,
    dietaryPreferences: "Vegetariano",
    allergen: ["Gluten", "Trigo"],
  },
  {
    name: "Hamburguesa Vegetariana",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920200/restaurantes%20y%20usuarios/hamburguer/hambur_novopj.jpg",
    description: "Una hamburguesa vegetariana con aguacate y queso cheddar",
    price: 10.5,
    dietaryPreferences: "Halal",
    allergen: ["Gluten", "Lácteos", "Huevos", "Soja", "Trigo"],
  },
];

module.exports = comidas;
