const comidas = [
  {
    name: "Filete de Ternera",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920200/restaurantes%20y%20usuarios/hamburguer/Filete_hklnsb.jpg",
    description: "Un delicioso filete de ternera a la parrilla",
    price: 24.5,
    dietaryPreferences: "Carnivore",
    allergen: {
      gluten: false,
      dairy: false,
      eggs: false,
      peanuts: false,
      treeNuts: false,
      soy: false,
      fish: false,
      shellfish: false,
      wheat: false,
      mustard: false,
      sesame: false,
      celery: false,
      sulphurDioxide: false,
      molluscs: false,
    },
    spicy: 2,
  },
  {
    name: "Salmón a la Parrilla",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920201/restaurantes%20y%20usuarios/hamburguer/salmon_lqftgu.jpg",
    description: "Un saludable salmón a la parrilla con limón y eneldo",
    price: 22.0,
    dietaryPreferences: "Pescatarian",
    allergen: {
      gluten: false,
      dairy: false,
      eggs: false,
      peanuts: false,
      treeNuts: false,
      soy: false,
      fish: true,
      shellfish: false,
      wheat: false,
      mustard: false,
      sesame: false,
      celery: false,
      sulphurDioxide: false,
      molluscs: false,
    },
    spicy: 1,
  },
  {
    name: "Ensalada César",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920200/restaurantes%20y%20usuarios/hamburguer/cesar_zguaie.jpg",
    description: "Una fresca ensalada César con pollo a la parrilla",
    price: 15.0,
    dietaryPreferences: "Vegetarian",
    allergen: {
      gluten: true,
      dairy: true,
      eggs: true,
      peanuts: false,
      treeNuts: false,
      soy: false,
      fish: false,
      shellfish: false,
      wheat: true,
      mustard: false,
      sesame: false,
      celery: false,
      sulphurDioxide: false,
      molluscs: false,
    },
    spicy: 1,
  },
  {
    name: "Pasta Alfredo",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920200/restaurantes%20y%20usuarios/hamburguer/pasta_lvunjq.jpg",
    description: "Pasta Alfredo cremosa con champiñones y parmesano",
    price: 18.5,
    dietaryPreferences: "Vegetarian",
    allergen: {
      gluten: true,
      dairy: true,
      eggs: false,
      peanuts: false,
      treeNuts: false,
      soy: false,
      fish: false,
      shellfish: false,
      wheat: true,
      mustard: false,
      sesame: false,
      celery: false,
      sulphurDioxide: false,
      molluscs: false,
    },
    spicy: 1,
  },
  {
    name: "Pizza Margarita",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920201/restaurantes%20y%20usuarios/hamburguer/piza_fwhq44.webp",
    description: "Una clásica pizza Margarita con tomate y mozzarella",
    price: 12.0,
    dietaryPreferences: "Vegetarian",
    allergen: {
      gluten: true,
      dairy: true,
      eggs: false,
      peanuts: false,
      treeNuts: false,
      soy: false,
      fish: false,
      shellfish: false,
      wheat: true,
      mustard: false,
      sesame: false,
      celery: false,
      sulphurDioxide: false,
      molluscs: false,
    },
    spicy: 1,
  },
  {
    name: "Enchiladas de Pollo",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920200/restaurantes%20y%20usuarios/hamburguer/enchilada_kzhg7m.jpg",
    description: "Enchiladas de pollo con salsa de tomate picante",
    price: 14.5,
    dietaryPreferences: "Carnivore",
    allergen: {
      gluten: true,
      dairy: true,
      eggs: false,
      peanuts: false,
      treeNuts: false,
      soy: false,
      fish: false,
      shellfish: false,
      wheat: true,
      mustard: false,
      sesame: false,
      celery: false,
      sulphurDioxide: false,
      molluscs: false,
    },
    spicy: 3,
  },
  {
    name: "Ensalada de Quinua",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920202/restaurantes%20y%20usuarios/hamburguer/quinua_ez1pwj.jpg",
    description: "Ensalada de quinua con aguacate y pimientos",
    price: 16.0,
    dietaryPreferences: "Vegan",
    allergen: {
      gluten: false,
      dairy: false,
      eggs: false,
      peanuts: false,
      treeNuts: false,
      soy: false,
      fish: false,
      shellfish: false,
      wheat: false,
      mustard: false,
      sesame: false,
      celery: false,
      sulphurDioxide: false,
      molluscs: false,
    },
    spicy: 1,
  },
  {
    name: "Tacos de Carne Asada",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920201/restaurantes%20y%20usuarios/hamburguer/tacos_vgpbji.jpg",
    description: "Tacos de carne asada con cebolla y cilantro",
    price: 13.5,
    dietaryPreferences: "Carnivore",
    allergen: {
      gluten: true,
      dairy: false,
      eggs: false,
      peanuts: false,
      treeNuts: false,
      soy: false,
      fish: false,
      shellfish: false,
      wheat: true,
      mustard: false,
      sesame: false,
      celery: false,
      sulphurDioxide: false,
      molluscs: false,
    },
    spicy: 4,
  },
  {
    name: "Sopa de Tomate",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920201/restaurantes%20y%20usuarios/hamburguer/sopa_ezcnta.webp",
    description: "Sopa de tomate casera con crutones",
    price: 8.0,
    dietaryPreferences: "Vegetarian",
    allergen: {
      gluten: true,
      dairy: false,
      eggs: false,
      peanuts: false,
      treeNuts: false,
      soy: false,
      fish: false,
      shellfish: false,
      wheat: true,
      mustard: false,
      sesame: false,
      celery: false,
      sulphurDioxide: false,
      molluscs: false,
    },
    spicy: 1,
  },
  {
    name: "Hamburguesa Vegetariana",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692920200/restaurantes%20y%20usuarios/hamburguer/hambur_novopj.jpg",
    description: "Una hamburguesa vegetariana con aguacate y queso cheddar",
    price: 10.5,
    dietaryPreferences: "Vegetarian",
    allergen: {
      gluten: true,
      dairy: true,
      eggs: true,
      peanuts: false,
      treeNuts: false,
      soy: true,
      fish: false,
      shellfish: false,
      wheat: true,
      mustard: false,
      sesame: false,
      celery: false,
      sulphurDioxide: false,
      molluscs: false,
    },
    spicy: 2,
  },
];

module.exports = comidas