const restaurantes = [
  {
    name: "El Rincón de María",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302078/restaurantes%20y%20usuarios/16825942691175_cpljt0.jpg",
    description:
      "Platos caseros con recetas tradicionales y ambiente acogedor.",
    city: "Barcelona",
    score: 9.5,
    coments: ["¡Me encantó la comida y el ambiente! Muy recomendado."],
  },
  {
    name: "La Brasserie Élégante",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302076/restaurantes%20y%20usuarios/16430402537419_zyl84k.jpg",
    description: "Comida gourmet francesa con toques modernos.",
    city: "París",
    score: 8.8,
    coments: ["La comida estuvo bien, pero el servicio podría mejorar."],
  },
  {
    name: "Sabor Mexicano",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302075/restaurantes%20y%20usuarios/La_20Mamona_20Castellana_18_il7r8f.webp",
    description: "Especialidades mexicanas auténticas en un entorno vibrante.",
    city: "city de México",
    score: 7.2,
    coments: [
      "El ambiente es genial, pero la comida no estuvo a la altura.",
    ],
  },
  {
    name: "Parrilla Argenta",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302076/restaurantes%20y%20usuarios/restaurantes-1_oxagcm.jpg",
    description: "Carnes asadas argentinas con los mejores cortes.",
    city: "Buenos Aires",
    score: 5.0,
    coments: ["La carne estuvo espectacular, ¡volveré por más!"],
  },
  {
    name: "Tokyo Sushi",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302075/restaurantes%20y%20usuarios/restaurantes_sahy7y.jpg",
    description: "Sushi fresco y variado con un toque japonés.",
    city: "Tokio",
    score: 4.5,
    coments: ["El sushi es delicioso, pero el servicio es lento."],
  },
  {
    name: "Fusión Oriental",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302075/restaurantes%20y%20usuarios/mejores-restaurantes-de-san-pedro-de-alcantara_jwdjly.jpg",
    description: "Una mezcla de sabores asiáticos en cada plato.",
    city: "Bangkok",
    score: 7.7,
    coments: ["El ambiente es genial, pero la comida no me impresionó."],
  },
  {
    name: "La Pizzería del Pueblo",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302074/restaurantes%20y%20usuarios/septimo-osteria-1_rn3pmg.webp",
    description: "Pizzas artesanales con ingredientes locales y frescos.",
    city: "Nápoles",
    score: 8.9,
    coments: ["Las pizzas son deliciosas y auténticas."],
  },
  {
    name: "Mariscos del Mar",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302074/restaurantes%20y%20usuarios/lista-recomendados_d7r6u8.jpg",
    description: "Delicias del mar servidas en un ambiente costero.",
    city: "Lisboa",
    score: 9.3,
    coments: [
      "Los mariscos son frescos y sabrosos, pero el precio es alto.",
    ],
  },
  {
    name: "Café del Arte",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302074/restaurantes%20y%20usuarios/restaurante-madrid_bzyrpe.jpg",
    description: "Cafetería acogedora con repostería y arte local.",
    city: "Viena",
    score: 7.8,
    coments: [
      "El café es excelente, pero las opciones de comida son limitadas.",
    ],
  },
  {
    name: "El Fogón Andaluz",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302074/restaurantes%20y%20usuarios/16273067638727_oi4ait.webp",
    description: "Sabores españoles con platos tradicionales de Andalucía.",
    city: "Sevilla",
    score: 8.6,
    coments: ["Las tapas son deliciosas y auténticas."],
  },
  {
    name: "Gourmet del Bosque",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302074/restaurantes%20y%20usuarios/santa-luzia_k8dmgn.jpg",
    description: "Comida de autor inspirada en ingredientes silvestres.",
    city: "Estocolmo",
    score: 9.8,
    coments: [
      "Una experiencia culinaria única, definitivamente vale la pena.",
    ],
  },
  {
    name: "Sabor Oriental",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302074/restaurantes%20y%20usuarios/olenna-cdmx_gv8pbv.webp",
    description: "Especialidades asiáticas auténticas en un entorno moderno.",
    city: "Tokio",
    score: 7.5,
    coments: [
      "Los sabores son auténticos, pero las porciones son pequeñas.",
      "No me gustó mucho la experiencia, no volveré.",
    ],
  },
  {
    name: "El Rincón del Mar",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302073/restaurantes%20y%20usuarios/donde-comer-en-santiago-de-compostela_pazkij.jpg",
    description: "Mariscos frescos y platos costeros con vista al océano.",
    city: "Sydney",
    score: 9.7,
    coments: [
      "La vista al mar es increíble, la comida es buena.",
      "Me decepcionó la calidad de los mariscos.",
      "Un lugar perfecto para una cena romántica.",
    ],
  },
  {
    name: "La Tavola Italiana",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302073/restaurantes%20y%20usuarios/16273807770497_wde7pv.webp",
    description: "Cocina italiana clásica con ingredientes importados.",
    city: "Roma",
    score: 8.4,
    coments: ["La pasta es auténtica y deliciosa."],
  },
  {
    name: "La Brasa Criolla",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302073/restaurantes%20y%20usuarios/Burj_Al_Arab_Al_Mahara-restaurante-submarino-a.jpg_occlfu.webp",
    description: "Carnes asadas a la brasa con sazón criollo.",
    city: "Lima",
    score: 9.1,
    coments: [
      "La carne asada tiene un sabor espectacular.",
      "La atención al cliente podría mejorar.",
    ],
  },
  {
    name: "Asia Fusion",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302073/restaurantes%20y%20usuarios/v2-grancanaria.elchurrasco_uivibi.jpg",
    description: "Una experiencia culinaria que fusiona sabores asiáticos.",
    city: "Bangkok",
    score: 6.2,
    coments: [
      "Los platos son creativos y sabrosos, pero el ambiente es ruidoso.",
      "No fue lo que esperaba en términos de sabor.",
    ],
  },
  {
    name: "La Cabaña del Sabor",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302073/restaurantes%20y%20usuarios/la-terraza-de-cuna-el_umacoj.jpg",
    description: "Platos rústicos y tradicionales en un ambiente rural.",
    city: "Oaxaca",
    score: 7.3,
    coments: [
      "La comida es auténtica y reconfortante.",
      "El lugar es pintoresco pero la comida no es memorable.",
    ],
  },
  {
    name: "Parrilla del Gaucho",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302073/restaurantes%20y%20usuarios/mixed-starter_juqbao.jpg",
    description: "Carnes asadas al estilo gaucho con auténtico sabor.",
    city: "Buenos Aires",
    score: 5.4,
    coments: ["La carne es tierna y jugosa, lo mejor de la parrilla."],
  },
  {
    name: "Maki Land",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302072/restaurantes%20y%20usuarios/31238005_pegfyt.jpg",
    description: "Variedad de makis y sushi creativos para todos los gustos.",
    city: "Tokio",
    score: 8.0,
    coments: [
      "La variedad de makis es impresionante, pero el arroz estaba un poco duro.",
      "No volveré, la calidad no se compara con otros lugares.",
    ],
  },
  {
    name: "Sabores del Mundo",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302072/restaurantes%20y%20usuarios/16273231601198_kzhxcb.webp",
    description: "Una selección de platos internacionales en un solo lugar.",
    city: "París",
    score: 4.2,
    coments: [
      "La variedad de platos es excelente, pero los precios son altos.",
      "Una experiencia gastronómica única que vale la pena.",
    ],
  },
  {
    name: "La Delicia Mediterránea",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302072/restaurantes%20y%20usuarios/16242826058936_hs4fid.webp",
    description: "Sabores mediterráneos con ingredientes frescos.",
    city: "Barcelona",
    score: 8.3,
    coments: [
      "Los sabores son auténticos y la presentación es hermosa.",
      "No estuvo mal, pero esperaba un poco más de sabor.",
    ],
  },
  {
    name: "Gourmet en el Puerto",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302072/restaurantes%20y%20usuarios/636ec9b036dfd_h4fqns.jpg",
    description: "Experiencia gastronómica con vistas al mar.",
    city: "Lisboa",
    score: 9.9,
    coments: [
      "La vista al mar es increíble y la comida deliciosa.",
      "Un lugar perfecto para una ocasión especial.",
    ],
  },
  {
    name: "Cocina Auténtica",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302072/restaurantes%20y%20usuarios/16199028897670_rps1uq.webp",
    description: "Platos tradicionales con autenticidad en cada bocado.",
    city: "Oporto",
    score: 3.7,
    coments: ["La comida es auténtica y casera, como la de la abuela."],
  },
  {
    name: "Aroma de Lima",
    img: "https://res.cloudinary.com/dxnzcewsy/image/upload/v1692302072/restaurantes%20y%20usuarios/kekale-casual-fine-dining_sfolm3.jpg",
    description: "Sabores peruanos en un ambiente cálido y amigable.",
    city: "Lima",
    score: 9.8,
    coments: [
      "La comida peruana es siempre una delicia, este lugar no decepcionó.",
      "Me encantó el ceviche, definitivamente regresaré.",
      "El ambiente es agradable pero la comida no es auténtica.",
    ],
  },
];

module.exports = restaurantes;
