const restaurantes = [
  {
    nombre: "El Rincón de María",
    foto: "restaurante1.jpg",
    descripcion:
      "Platos caseros con recetas tradicionales y ambiente acogedor.",
    ciudad: "Ciudad A",
    puntos: 10,
  },
  {
    nombre: "La Brasserie Élégante",
    foto: "restaurante2.jpg",
    descripcion: "Comida gourmet francesa con toques modernos.",
    ciudad: "Ciudad B",
    puntos: 10,
  },
  {
    nombre: "Sabor Mexicano",
    foto: "restaurante3.jpg",
    descripcion: "Especialidades mexicanas auténticas en un entorno vibrante.",
    ciudad: "Ciudad C",
    puntos: 7.5,
  },
  {
    nombre: "Parrilla Argenta",
    foto: "restaurante4.jpg",
    descripcion: "Carnes asadas argentinas con los mejores cortes.",
    ciudad: "Ciudad D",
    puntos: 8.5,
  },
  {
    nombre: "Tokyo Sushi",
    foto: "restaurante5.jpg",
    descripcion: "Sushi fresco y variado con un toque japonés.",
    ciudad: "Ciudad E",
    puntos: 8,
  },
  {
    nombre: "Fusión Oriental",
    foto: "restaurante6.jpg",
    descripcion: "Una mezcla de sabores asiáticos en cada plato.",
    ciudad: "Ciudad F",
    puntos: 7,
  },
  {
    nombre: "La Pizzería del Pueblo",
    foto: "restaurante7.jpg",
    descripcion: "Pizzas artesanales con ingredientes locales y frescos.",
    ciudad: "Ciudad G",
    puntos: 9,
  },
  {
    nombre: "Mariscos del Mar",
    foto: "restaurante8.jpg",
    descripcion: "Delicias del mar servidas en un ambiente costero.",
    ciudad: "Ciudad H",
    puntos: 9.5,
  },
  {
    nombre: "Café del Arte",
    foto: "restaurante9.jpg",
    descripcion: "Cafetería acogedora con repostería y arte local.",
    ciudad: "Ciudad I",
    puntos: 7.5,
  },
  {
    nombre: "El Fogón Andaluz",
    foto: "restaurante10.jpg",
    descripcion: "Sabores españoles con platos tradicionales de Andalucía.",
    ciudad: "Ciudad J",
    puntos: 8.5,
  },
  {
    nombre: "Gourmet del Bosque",
    foto: "restaurante11.jpg",
    descripcion: "Comida de autor inspirada en ingredientes silvestres.",
    ciudad: "Ciudad K",
    puntos: 10,
  },
  {
    nombre: "Sabor Oriental",
    foto: "restaurante12.jpg",
    descripcion: "Especialidades asiáticas auténticas en un entorno moderno.",
    ciudad: "Ciudad L",
    puntos: 6.5,
  },
  {
    nombre: "El Rincón del Mar",
    foto: "restaurante13.jpg",
    descripcion: "Mariscos frescos y platos costeros con vista al océano.",
    ciudad: "Ciudad M",
    puntos: 10,
  },
  {
    nombre: "La Tavola Italiana",
    foto: "restaurante14.jpg",
    descripcion: "Cocina italiana clásica con ingredientes importados.",
    ciudad: "Ciudad N",
    puntos: 8.5,
  },
  {
    nombre: "La Brasa Criolla",
    foto: "restaurante15.jpg",
    descripcion: "Carnes asadas a la brasa con sazón criollo.",
    ciudad: "Ciudad O",
    puntos: 9,
  },
  {
    nombre: "Asia Fusion",
    foto: "restaurante16.jpg",
    descripcion: "Una experiencia culinaria que fusiona sabores asiáticos.",
    ciudad: "Ciudad P",
    puntos: 8.5,
  },
  {
    nombre: "La Cabaña del Sabor",
    foto: "restaurante17.jpg",
    descripcion: "Platos rústicos y tradicionales en un ambiente rural.",
    ciudad: "Ciudad Q",
    puntos: 7,
  },
  {
    nombre: "Parrilla del Gaucho",
    foto: "restaurante18.jpg",
    descripcion: "Carnes asadas al estilo gaucho con auténtico sabor.",
    ciudad: "Ciudad R",
    puntos: 9,
  },
  {
    nombre: "Maki Land",
    foto: "restaurante19.jpg",
    descripcion: "Variedad de makis y sushi creativos para todos los gustos.",
    ciudad: "Ciudad S",
    puntos: 8,
  },
  {
    nombre: "Sabores del Mundo",
    foto: "restaurante20.jpg",
    descripcion: "Una selección de platos internacionales en un solo lugar.",
    ciudad: "Ciudad T",
    puntos: 9,
  },
];

module.exports = restaurantes;